name: aldia
description: AlDía – Sistema de Gestión y Notificación de Pagos de Arriendo
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.6.0
  flutter_secure_storage: ^9.0.0
  provider: ^6.1.1
  google_fonts: ^8.1.0
  pdf: ^3.10.8
  printing: ^5.12.0
  file_picker: ^8.0.0
  url_launcher: ^6.2.0
  intl: ^0.20.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/login_background.jpg